Added my profile page and modified home page
galasa-dev/webui pull request #49
Opened 2024-08-22 12:44 UTC by aashir21

Signed-off-by: Aashir Siddiqui <aashir_sidiki@hotmail.com>

2024-08-22 12:50 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-webui-pr-49-mvwz6 for details. If you are unable to do so, please contact a member of the Galasa team.

2024-08-22 12:55 UTC, galasa-team commented
Build successful

2024-08-22 13:02 UTC, galasa-team commented
Build successful

2024-08-22 14:53 UTC, eamansour requested changes
Good progress! Just a few comments :)

Also, it would be good to have a few screenshots in the PR description to make reviewing visual changes a bit easier.

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/app/layout.tsx
> +'use client'
We don't want to render the layout on the client - better to make individual client components

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/app/myprofile/page.tsx
> +import "../../styles/global.scss"
I don't think we need to import the global styles in every page - same applies throughout this PR

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/app/myprofile/page.tsx
> +            console.log(err);
Would be good to display an error notification somewhere, otherwise the user would get an empty page

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/utils/user.ts
> +}
This is mostly duplicated from the auth utils, it would be good to refactor this alongside the auth utils.

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/app/page.tsx
> +      <PageTile data-testid="page-tile" title={"Home"} />
`data-testid` can be easily overused and ends up littering the code with code specific to tests, is there another way we can grab an element for testing purposes?

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/assets/images/homeGraphic.png
I would put images in `public` - see https://nextjs.org/docs/app/building-your-application/optimizing/static-assets

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/components/LeftHeaderMenu.tsx
> +        </OverflowMenu>
Shouldn't this be a sidebar that slides open? It currently opens up like the menu on the top right

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/styles/HomeContent.module.css
> +.heroImage{
Missing copyright

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/components/HomeContent.tsx
> +                    <h4>Get the most from your Galasa experience by reading the Galasa documentation &nbsp;
This is being rendered with extra spacing between `documentation` and the `here` link - wouldn't it be better to put the link around `Galasa documentation`?

2024-08-22 14:53 UTC, eamansour commented on galasa-ui/src/components/HomeContent.tsx
> +                        <a href="https://galasa.dev/" target="_blank">here</a>
Missing `rel="noopener noreferrer"`
Also might be worth using NextJS' `<Link>` here https://nextjs.org/docs/app/api-reference/components/link

2024-08-23 12:29 UTC, galasa-team commented
Build successful

2024-08-23 12:54 UTC, eamansour commented on galasa-ui/src/app/auth/tokens/route.ts
> +  const authApiClientWithAuthHeader = new AuthenticationAPIApi(createAuthenticatedApiConfiguration(GALASA_API_SERVER_URL, bearerTokenCookie))
`getApiClientWithAuthHeader` doesn't indicate that it now returns a bearer token.

Also, we can change the `createAuthenticatedApiConfiguration` to get the bearer token and API server URL within the function instead of as parameters. That way we won't need to pass the `GALASA_API_SERVER_URL` everywhere and the code would become:

```ts
const authApiClient = new AuthenticationAPIApi(createAuthenticatedApiConfiguration());
```

2024-08-23 12:54 UTC, eamansour commented on galasa-ui/src/app/auth/tokens/route.ts
> +const GALASA_API_SERVER_URL = process.env.GALASA_API_SERVER_URL ?? '';
The API server URL can be imported if needed, I don't think you need to redefine it everywhere

2024-08-23 12:54 UTC, eamansour commented on galasa-ui/src/app/myprofile/page.tsx
> +                    <h4>Currently logged in as: </h4>
Extra space at the end of this header can be removed

2024-08-23 12:54 UTC, eamansour commented on galasa-ui/src/components/HomeContent.tsx
> +                        <Link href="https://galasa.dev/" target="_blank" rel="noopener noreferrer"> Galasa documentation</Link>
The space before `Galasa` in the link can be removed

2024-08-23 12:54 UTC, eamansour commented on galasa-ui/src/utils/user.ts
> +}
This isn't being used anywhere so we can remove this file - also we won't be using the `getUserData` method since we'll use the OpenAPI-generated client methods to interact with the REST API.

2024-08-23 13:17 UTC, eamansour approved these changes

2024-08-23 13:21 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-webui-pr-49-s4mtq for details. If you are unable to do so, please contact a member of the Galasa team.

2024-08-23 13:36 UTC, galasa-team commented
Build successful

2024-08-23 13:37 UTC, merged